export const shoppingItems = [
    {
      id: 1,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: "Herschel Heritage Backpack | XL",
      rating: 4.5,
      price: "$200",
    },
    {
      id: 2,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Little American Backpack | Premium  Classics - 30l',
      rating: 4.5,
      price: "$245",
    },
    {
      id: 3,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Retreat™ Backpack 23L',
      rating: 4.5,
      price: "$300",
    },
    {
      id: 4,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Kasio Backpack | Tech-30L',
      rating: 4.5,
      price: "$320",
    },
    {
      id: 5,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text:'Kasio Backpack | Sch - 30L',
      rating: 4.5,
      price: "$240",
    },
    {
      id: 6,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Little America Backpack | Sch - 30L',
      rating: 4.5,
      price: "$130",
    },
    {
      id: 7,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text:  'Little America Backpack | Classics - 30L',
      rating: 4.5,
      price: "$200",
    },
    {
      id: 8,
      image: "/images/bag8.png",
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Kasio Backpack |  Sch -XL',
      rating: 4.5,
      price: "$245",
    },
    {
      id: 9,
      images: [
        "/images/bag1.png",
        "/images/bag2.png",
        "/images/bag3.png",
        "/images/bag4.png",
        "/images/bag5.png",
        "/images/bag6.png",
        "/images/bag7.png",
        "/images/bag8.png",
        "/images/bag9.png",
      ],
      text: 'Cosmoa Backpack | Travel - 30L',
      rating: 4.5,
      price: "$400",
    },
  ];
  